### ISSUE TITLE
A programmatic API?

### ISSUE THREAD

**Issue by tomek-he-him** [tmcw-up-for-adoption/doxme#4]
Hi, thanks for a great tool.

Have you considered adding a programmatic API? Maybe as simple as `doxme(doxOutput)`.

I'll be happy to write a gulp plugin for you if there is an API.

**Comment by tmcw** [comment]
Yep, sounds reasonable. JSON in, string out?

**Comment by tmcw** [comment]
Added in 1.5.0

**Comment by tomek-he-him** [comment]
Wow, thanks for the promptness :) Looks great to me! :+1:

**Comment by tomek-he-him** [comment]
@tmcw so the gulp plugin is [ready](https://github.com/tomekwi/gulp-doxme). Let me know if you have any thoughts regarding the API and such.
